### ISSUE TITLE
Getting error from `distance` between two ALBERT models

### ISSUE THREAD

**Issue by quantitative-technologies** [CalculatedContent/WeightWatcher#149]
My code was working earlier but seems to have broken due to updating my weightwatcher version.

Here is an example script:

```
from transformers import AutoModelForSequenceClassification
from weightwatcher import WeightWatcher


if __name__ == "__main__":
    output_dir = ...set accordingly...
    pretrained_model_path = output_dir / 'checkpoint-0'
    pretrained_model_sc = AutoModelForSequenceClassification.from_pretrained(pretrained_model_path)

    COMPARISON_STEP = 20
    finetuned_model_path = output_dir / f'checkpoint-{COMPARISON_STEP}'
    finetuned_model_sc = AutoModelForSequenceClassification.from_pretrained(finetuned_model_path)

    ww = WeightWatcher()
    distances = ww.distances(pretrained_model_sc, finetuned_model_sc)
```

The two checkpoints I used are: [checkpoint-0](https://drive.google.com/drive/folders/11F1hb4foTjFmd3NcRpU4mZm1zBniUL_G?usp=sharing) and [checkpoint-20](https://drive.google.com/drive/folders/11QH_Q8xVu-P3Uh3gNGgZAyh0ycO4QmTz?usp=sharing)

When I ran this code from the console it gave the error:
```
INFO:weightwatcher:

python      version 3.7.15 (default, Oct 12 2022, 19:14:55) 
[GCC 7.5.0]
numpy       version 1.21.6
tensforflow version 2.9.2
keras       version 2.9.0
Traceback (most recent call last):
  File "debug-ww-distances.py", line 16, in <module>
    distances = ww.distances(pretrained_model_sc, finetuned_model_sc)
  File "<string>", line 197, in B
  File "/usr/local/lib/python3.7/dist-packages/weightwatcher/weightwatcher.py", line 1173, in distances
    layer_iter_1 = WWLayerIterator(model_1)
  File "/usr/local/lib/python3.7/dist-packages/weightwatcher/weightwatcher.py", line 729, in __init__
    super().__init__(model, params=params)
  File "/usr/local/lib/python3.7/dist-packages/weightwatcher/weightwatcher.py", line 610, in __init__
    self.k = params[START_IDS] # 0 | 1
KeyError: 'layer_ids_start'
```

Oddly, the equivalent code running in colab gave:
```
INFO:weightwatcher:

python      version 3.7.15 (default, Oct 12 2022, 19:14:55) 
[GCC 7.5.0]
numpy       version 1.21.6
tensforflow version 2.9.2
keras       version 2.9.0
ERROR:weightwatcher:Sorry, problem comparing models

---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

[/usr/local/lib/python3.7/dist-packages/pandas/core/internals/managers.py](https://localhost:8080/#) in create_block_manager_from_arrays(arrays, names, axes, consolidate)
   1773         blocks = _form_blocks(arrays, names, axes, consolidate)
-> 1774         mgr = BlockManager(blocks, axes)
   1775     except ValueError as e:

8 frames

[/usr/local/lib/python3.7/dist-packages/pandas/core/internals/managers.py](https://localhost:8080/#) in __init__(self, blocks, axes, verify_integrity)
    913 
--> 914             self._verify_integrity()
    915 

[/usr/local/lib/python3.7/dist-packages/pandas/core/internals/managers.py](https://localhost:8080/#) in _verify_integrity(self)
    920             if block.shape[1:] != mgr_shape[1:]:
--> 921                 raise construction_error(tot_items, block.shape[1:], self.axes)
    922         if len(self.items) != tot_items:

ValueError: Shape of passed values is (2, 4), indices imply (1, 4)


During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)

[/usr/local/lib/python3.7/dist-packages/weightwatcher/weightwatcher.py](https://localhost:8080/#) in distances(self, model_1, model_2)
   1197                     #details = details.append(data, ignore_index=True)
-> 1198                     data_df = pd.DataFrame.from_records(data , index=[0])
   1199                     details = pd.append([details, data_df])

[/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py](https://localhost:8080/#) in from_records(cls, data, index, exclude, columns, coerce_float, nrows)
   2121         manager = get_option("mode.data_manager")
-> 2122         mgr = arrays_to_mgr(arrays, arr_columns, result_index, columns, typ=manager)
   2123 

[/usr/local/lib/python3.7/dist-packages/pandas/core/internals/construction.py](https://localhost:8080/#) in arrays_to_mgr(arrays, arr_names, index, columns, dtype, verify_integrity, typ, consolidate)
    135         return create_block_manager_from_arrays(
--> 136             arrays, arr_names, axes, consolidate=consolidate
    137         )

[/usr/local/lib/python3.7/dist-packages/pandas/core/internals/managers.py](https://localhost:8080/#) in create_block_manager_from_arrays(arrays, names, axes, consolidate)
   1775     except ValueError as e:
-> 1776         raise construction_error(len(arrays), arrays[0].shape, axes, e)
   1777     if consolidate:

ValueError: Shape of passed values is (2, 4), indices imply (1, 4)


During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)

[<ipython-input-43-20a1bf693c3b>](https://localhost:8080/#) in <module>
      6 
      7 ww = WeightWatcher()
----> 8 distances = ww.distances(pretrained_model_sc, finetuned_model_sc)
      9 print(f'Average distance: {distances[0]}')
     10 distances[1]

/usr/local/lib/python3.7/dist-packages/telly.py in B(*I, **J)

[/usr/local/lib/python3.7/dist-packages/weightwatcher/weightwatcher.py](https://localhost:8080/#) in distances(self, model_1, model_2)
   1200         except:
   1201             logger.error("Sorry, problem comparing models")
-> 1202             raise Exception("Sorry, problem comparing models")
   1203 
   1204         details.set_index('layer_id', inplace=True)

Exception: Sorry, problem comparing models
```

**Comment by charlesmartin14** [comment]
This is fixed in on main  branch now
Will deploy to test pypi shortly

**Comment by quantitative-technologies** [comment]
Good, I can test it as soon as it is in test pypi.

**Comment by charlesmartin14** [comment]
the bug was setting W_shape to a tuple
This has been changed to just listing N and M as with the analyze details dataframe

**Comment by quantitative-technologies** [comment]
Thanks. I will see it once it gets into testing.

**Comment by quantitative-technologies** [comment]
All good now.
