### ISSUE TITLE
FAST SVD fails on CPU for conv2d_ftt case

### ISSUE THREAD

**Issue by charlesmartin14** [CalculatedContent/WeightWatcher#207]
see

```
def test_conv2d_fft(self):
		"""Test the FFT method"; why does this fail ? """
		
		details = self.watcher.describe(layers=[self.first_layer], conv2d_fft=True)
		print(details)
		
		details = self.watcher.analyze(layers=[self.first_layer], conv2d_fft=True)
		actual = details.alpha.to_numpy()[0]
		expected = 2.144
		self.assertAlmostEqual(actual,expected, places=4)
```

The error message is

```
ERROR: test_conv2d_fft (tests.test.Test_VGG11_Alpha_w_WWFit)
Test the FFT method"; why does this fail ?
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/charleshmartin/Desktop/work/weightwatcher/github/WeightWatcher/tests/test.py", line 2266, in test_conv2d_fft
    details = self.watcher.analyze(layers=[self.first_layer], conv2d_fft=True)
  File "/Users/charleshmartin/Desktop/work/weightwatcher/github/WeightWatcher/weightwatcher/weightwatcher.py", line 2531, in analyze
    self.apply_esd(ww_layer, params)
  File "/Users/charleshmartin/Desktop/work/weightwatcher/github/WeightWatcher/weightwatcher/weightwatcher.py", line 1970, in apply_esd
    evals, sv_max, rank_loss = self.combined_eigenvalues(Wmats, N, M, n_comp, params)
  File "/Users/charleshmartin/Desktop/work/weightwatcher/github/WeightWatcher/weightwatcher/weightwatcher.py", line 1878, in combined_eigenvalues
    sv = svd_vals(W, method=params[SVD_METHOD])
  File "/Users/charleshmartin/Desktop/work/weightwatcher/github/WeightWatcher/weightwatcher/RMT_Util.py", line 82, in svd_vals
    if method == FAST_SVD:     return _svd_vals_fast(W)
  File "/Users/charleshmartin/Desktop/work/weightwatcher/github/WeightWatcher/weightwatcher/RMT_Util.py", line 33, in <lambda>
    _svd_vals_accurate = lambda W: sp.linalg.svd(W, compute_uv=False)
  File "/Users/charleshmartin/anaconda3/envs/ww0.6.5/lib/python3.9/site-packages/scipy/linalg/decomp_svd.py", line 110, in svd
    raise ValueError('expected matrix')
ValueError: expected matrix

----------------------------------------------------------------------
Ran 1 test in 41.849s

FAILED (errors=1)
```

**Comment by charlesmartin14** [comment]
Actually, IDK why this is failing... must be the old code is still using the nump linalg svd API somewhere

**Comment by charlesmartin14** [comment]
Stil trying to reproduce
