### ISSUE TITLE
Bug in the new GPU enabled WW_Powerlaw method

### ISSUE THREAD

**Issue by charlesmartin14** [CalculatedContent/WeightWatcher#236]
I found it trying to run the BLOOM models with fix_fingers='clip_xmax" on Google Colab with the GPU

I suspect it might be a general bug when combining the new PL method with fix_fingers ?

To reproduce this exactly, download the pytorch_model.bin file for the HF Bloom 3B model to a tmp directory (cache_dir) and use the new method.

`
details = ww.WeightWatcher.analyze_pytorch_bins(model_dir=cache_dir, plot=True, fix_fingers='clip_xmax', max_evals=15000, max_N=50000, detX=True, randomize=True, mp_fit=True)
`

**Bug report below**
```
INFO:weightwatcher:analyzing_pytorch_bin files in /content/drive/MyDrive/WW/BLOOM/bigscience-bloom-3b, returning combined details
INFO:weightwatcher:Processing model named: bloom
INFO:weightwatcher:loading /content/drive/MyDrive/WW/BLOOM/bigscience-bloom-3b/pytorch_model.bin
INFO:weightwatcher:

python      version 3.9.16 (main, Dec  7 2022, 01:11:51) 
[GCC 9.4.0]
numpy       version 1.22.4
torch version 1.13.1+cu116
INFO:weightwatcher:

python      version 3.9.16 (main, Dec  7 2022, 01:11:51) 
[GCC 9.4.0]
numpy       version 1.22.4
torch version 1.13.1+cu116
INFO:weightwatcher:Saving all images to ww-img
INFO:weightwatcher:Fixing fingers using  clip_xmax
INFO:weightwatcher:params {'glorot_fix': False, 'normalize': False, 'conv2d_norm': True, 'randomize': True, 'savedir': '/content/drive/MyDrive/WW/BLOOM/bigscience-bloom-3b-img', 'savefig': '/content/drive/MyDrive/WW/BLOOM/bigscience-bloom-3b-img', 'rescale': True, 'plot': True, 'deltaEs': False, 'intra': False, 'channels': None, 'fft': False, 'conv2d_fft': False, 'ww2x': False, 'pool': True, 'vectors': False, 'smooth': None, 'stacked': False, 'svd_method': 'fast', 'fix_fingers': 'clip_xmax', 'fit': 'power_law', 'MAX_FINGERS': 10, 'finger_thresh': 1.0, 'sparsify': True, 'detX': True, 'mp_fit': True, 'min_evals': 10, 'max_evals': 15000, 'max_N': 50000, 'tolerance': 1e-06, 'layer_ids_start': 0, 'add_biases': False, 'pl_package': 'ww', 'xmax': None, 'glorot_fit': False, 'layers': [], 'xmin_max': None}
INFO:weightwatcher:Saving all images to /content/drive/MyDrive/WW/BLOOM/bigscience-bloom-3b-img
INFO:weightwatcher:Fixing fingers using  clip_xmax
INFO:weightwatcher:torch version 1.13.1+cu116
INFO:weightwatcher:framework from model = 16
INFO:weightwatcher:Layer id 2  unknown type 1 layer  <class 'weightwatcher.weightwatcher.PyStateDictLayer'>
INFO:weightwatcher:Layer id 3  unknown type 1 layer  <class 'weightwatcher.weightwatcher.PyStateDictLayer'>
INFO:weightwatcher:fix the fingers by fitting a clipped power law using pl_package = ww, xmax=None
INFO:weightwatcher:fit_clipped_powerlaw: max_fingers=MAX_FINGERS xmax=None
INFO:weightwatcher:PL FIT running NEW power law method
INFO:weightwatcher:PL FIT running NEW power law method
INFO:weightwatcher:fix_fingers: idx=2 fit alpha 3.4835  sigma 0.1600 xmax=None
INFO:weightwatcher:PL FIT running NEW power law method
INFO:weightwatcher:fix_fingers: idx=3 fit alpha 3.5270  sigma 0.1648 xmax=None
INFO:weightwatcher:PL FIT running NEW power law method
INFO:weightwatcher:fix_fingers: idx=4 fit alpha 3.5658  sigma 0.1667 xmax=None
INFO:weightwatcher:PL FIT running NEW power law method
INFO:weightwatcher:fix_fingers: idx=5 fit alpha 3.6066  sigma 0.1726 xmax=None
INFO:weightwatcher:PL FIT running NEW power law method
INFO:weightwatcher:fix_fingers: idx=6 fit alpha 3.6484  sigma 0.1766 xmax=None
INFO:weightwatcher:PL FIT running NEW power law method
INFO:weightwatcher:fix_fingers: idx=7 fit alpha 3.6820  sigma 0.1800 xmax=None
INFO:weightwatcher:PL FIT running NEW power law method
INFO:weightwatcher:fix_fingers: idx=8 fit alpha 3.7254  sigma 0.1850 xmax=None
INFO:weightwatcher:PL FIT running NEW power law method
INFO:weightwatcher:fix_fingers: idx=9 fit alpha 3.7641  sigma 0.1903 xmax=None
INFO:weightwatcher:fix_fingers: checking final alpha, starting with idx=9, xmax=None
INFO:weightwatcher:PL FIT running NEW power law method
INFO:weightwatcher:checking fit 10  alpha 3.76 sigma 0.19  xmax None
INFO:weightwatcher:PL FIT running NEW power law method
INFO:weightwatcher:checking fit 11  alpha 3.76 sigma 0.19  xmax None
INFO:weightwatcher:PL FIT running NEW power law method
INFO:weightwatcher:checking fit 12  alpha 3.76 sigma 0.19  xmax None
ERROR:weightwatcher:Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/weightwatcher/weightwatcher.py", line 4493, in apply_watcher_to_pytorch_bins
    details = watcher.analyze(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/weightwatcher/weightwatcher.py", line 2654, in analyze
    self.apply_powerlaw(ww_layer, params)
  File "/usr/local/lib/python3.9/dist-packages/weightwatcher/weightwatcher.py", line 2263, in apply_powerlaw
    self.fit_powerlaw(evals, xmin=xmin, xmax=xmax, plot=plot, layer_name=layer_name, layer_id=layer_id, \
  File "/usr/local/lib/python3.9/dist-packages/weightwatcher/weightwatcher.py", line 3337, in fit_powerlaw
    fit.plot_power_law_pdf(color='r', linestyle='--', ax=fig2)
  File "/usr/local/lib/python3.9/dist-packages/weightwatcher/WW_powerlaw.py", line 102, in plot_power_law_pdf
    ax.plot(bins, PDF, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/matplotlib/axes/_axes.py", line 1688, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/usr/local/lib/python3.9/dist-packages/matplotlib/axes/_base.py", line 311, in __call__
    yield from self._plot_args(
  File "/usr/local/lib/python3.9/dist-packages/matplotlib/axes/_base.py", line 504, in _plot_args
    raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (238,) and (250,)
```

**Comment by charlesmartin14** [comment]
/usr/local/lib/python3.9/dist-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/content/WeightWatcher/weightwatcher/weightwatcher.py:2181: RuntimeWarning: divide by zero encountered in log10
  plt.hist(np.log10(evals), bins=100)
ERROR:weightwatcher:Traceback (most recent call last):
  File "/content/WeightWatcher/weightwatcher/weightwatcher.py", line 4496, in apply_watcher_to_pytorch_bins
    details = watcher.analyze(**kwargs)
  File "/content/WeightWatcher/weightwatcher/weightwatcher.py", line 2680, in analyze
    self.apply_detX(ww_layer, params=params)
  File "/content/WeightWatcher/weightwatcher/weightwatcher.py", line 2181, in apply_detX
    plt.hist(np.log10(evals), bins=100)
  File "/usr/local/lib/python3.9/dist-packages/matplotlib/pyplot.py", line 2645, in hist
    return gca().hist(
  File "/usr/local/lib/python3.9/dist-packages/matplotlib/__init__.py", line 1442, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/matplotlib/axes/_axes.py", line 6790, in hist
    m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
  File "<__array_function__ internals>", line 180, in histogram
  File "/usr/local/lib/python3.9/dist-packages/numpy/lib/histograms.py", line 793, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File "/usr/local/lib/python3.9/dist-packages/numpy/lib/histograms.py", line 426, in _get_bin_edges
    first_edge, last_edge = _get_outer_edges(a, range)
  File "/usr/local/lib/python3.9/dist-packages/numpy/lib/histograms.py", line 315, in _get_outer_edges
    raise ValueError(
ValueError: supplied range of [-inf, 2.0] is not finite
 
Occurs ar layer 11

**Comment by charlesmartin14** [comment]
This appears to be due to the fact that the layer is very weirdly scaled
There appears to be no detX solution

![image](https://user-images.githubusercontent.com/498448/229327618-77eee7ab-1df2-46eb-8def-1bddf5aa5af4.png)

**Comment by charlesmartin14** [comment]
the smaller float introduces much smaller near-zero eigenvalues, which causes the plot.hist(log(evals) fails

so in apply_detX() we need 
         ```
   nz_evals = evals[evals > EVALS_THRESH]
            plt.hist(np.log10(nz_evals), bins=100)
```
