### ISSUE TITLE
Problem with deepcopy on Keras U-Net models

### ISSUE THREAD

**Issue by charlesmartin14** [CalculatedContent/WeightWatcher#247]
We are seeing a problem with the U-Net models from Keras that occurs when using pool=False (ww2x=True) that causes the a problem on the deepcopy.  Here's the reported error

**Hello <@775053632956530748> when i add the pool=False argument i get the following error**

```
Traceback (most recent call last):
  File "/home/linux/PycharmProjects/pythonProject/ww_analyze_tf_3.py", line 146, in <module>
    details_3 = watcher.analyze(randomize=True, fix_fingers="clip_xmax", pool=False)
  File "/home/linux/ww/lib/python3.10/site-packages/weightwatcher/weightwatcher.py", line 2662, in analyze
    for ww_layer in layer_iterator:
  File "/home/linux/ww/lib/python3.10/site-packages/weightwatcher/weightwatcher.py", line 1070, in __next__
    return self.next()
  File "/home/linux/ww/lib/python3.10/site-packages/weightwatcher/weightwatcher.py", line 1073, in next
    curr_layer = next(self.layer_iter)
  File "/home/linux/ww/lib/python3.10/site-packages/weightwatcher/weightwatcher.py", line 1321, in ww_slice_iter_
    ww_slice = deepcopy(ww_layer)
  File "/usr/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  
... 
```

I can fix this but it will take a few days
One solution now would be to export the weights  from the keras model, and load them into a pyTorch U-Net model

In the mean time, I can try to either
- remove the deepcopy from weightwathcer (eh, might be hard)
- add the option to analyze the model weights directly (doable , will take time)

**Comment by charlesmartin14** [comment]
This is the suggested fix from ChatGPT for the keras layer

This could be added to the Keras Layer when it is created  when the underlying framework layer is set

```

# Assume 'layer' is the Keras layer object you want to copy
# First, create a new layer with the same configuration as the original layer
new_layer = keras.layers.deserialize(keras.layers.serialize(layer))

# Then, remove the inbound_nodes and outbound_nodes attributes from the new layer
new_layer.__dict__.pop('inbound_nodes', None)
new_layer.__dict__.pop('outbound_nodes', None)
```

# Now you can use deepcopy on the new layer object without worrying about copying links to other layers
deepcopy_layer = copy.deepcopy(new_layer)
